MoviesBlog/Controllers/MovieController.cs
using MoviesBlog.DAL;
using MoviesBlog.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MoviesBlog.Controllers
{
    public class MoviesController : Controller
    {
        private ProjectContext db = new ProjectContext();

        // GET: Movies
        public ActionResult Index(string searchName, string searchGenre, string searchReleaseDate, string searchLanguage, double? searchRate)
        {
            var results = db.Movies.AsQueryable();
            int releaseDate;
            Genre genre;
            Language language;
            if (!string.IsNullOrEmpty(searchName))
            {
                results = results.Where(s => s.Name.Contains(searchName));
            }
            if (!string.IsNullOrEmpty(searchGenre) && Enum.TryParse(searchGenre, out genre))
            {
                results = results.Where(s => s.Genre == genre);
            }
            if (!string.IsNullOrEmpty(searchLanguage) && Enum.TryParse(searchLanguage, out language))
            {
                results = results.Where(s => s.Language == language);
            }
            if (!string.IsNullOrEmpty(searchReleaseDate) && int.TryParse(searchReleaseDate, out releaseDate))
            {
                results = results.Where(s => s.ReleaseDate.Year >= releaseDate);
            }
            return View(results.ToList());
        }

        // GET: Movies
        [HttpGet]
        public ActionResult IndexData(string searchName, string searchGenre, string searchReleaseDate, string searchLanguage, double? searchRate)
        {
            var movies = db.Movies.ToList();

            return Json(movies, JsonRequestBehavior.AllowGet);
        }

        // GET: Movies/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // GET: Movies/Create
        [Authorize(Users = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "Admin")]
        public ActionResult Create(HttpPostedFileBase postedFile, [Bind(Include = "movieID,Name,Genre,ReleaseDate,Producer, RunningTime, Location, ImageName, Language")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                if (postedFile != null)
                {
                    movie.ImageName = Path.GetFileName(postedFile.FileName);


                    string path = Server.MapPath("~/Media/movies");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                    postedFile.SaveAs(path + "\\" + Path.GetFileName(postedFile.FileName));
                    ViewBag.Message = "File uploaded successfully.";
                }

                db.Movies.Add(movie);

                Map map = new Map
                {
                    Id = movie.Id,
                    Name = movie.Name,
                    Location = movie.Location
                };

                db.Maps.Add(map);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(movie);
        }

        // GET: Movies/Edit/5
        [Authorize(Users = "Admin")]
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "Admin")]
        public ActionResult Edit(HttpPostedFileBase postedFile, [Bind(Include = "movieID,Name,Genre,ReleaseDate,Producer,Location,RunningTime,Language,ImageName")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();

                if (postedFile != null)
                {
                    movie.ImageName = Path.GetFileName(postedFile.FileName);

                    string path = Server.MapPath("~/Media/movies");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                    postedFile.SaveAs(path + "\\" + Path.GetFileName(postedFile.FileName));
                    ViewBag.Message = "File uploaded successfully.";
                    movie.ImageName = Path.GetFileName(postedFile.FileName);

                }

                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        [Authorize(Users = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "Admin")]
        public ActionResult Delete(int id)
        {
            Movie movie = db.Movies.Find(id);
            var posts = db.Posts.Where(p => p.MovieId == id);
            foreach (var post in posts)
            {
                db.Posts.Remove(post);
            }
                db.SaveChanges();

            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Trailer
        public ActionResult Trailer(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }

            return View("Trailer", movie);
        }

        // GET: Posts
        public ActionResult PieChart()
        {
            return View("Pie");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MoviesBlog/Views/Movies/Create.cshtml
@model MoviesBlog.Models.Movie

@{
    ViewBag.Title = "Create";
}

<h2>Create movie</h2>

@using (Html.BeginForm("Create", "Movies", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
        @Html.AntiForgeryToken()

        <div class="form-horizontal" style="font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="fields-row">
                <div class="movie-field">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="movie-field">
                    @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.Genre, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="fields-row">
                <div class="movie-field">
                    @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="movie-field">
                    @Html.LabelFor(model => model.Producer, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Producer, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Producer, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="fields-row">
                <div class="movie-field">
                    @Html.LabelFor(model => model.RunningTime, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.RunningTime, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RunningTime, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="movie-field">
                    @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.Language, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
                    </div>
                </div>
             </div>

            <div class="fields-row">
                <div class="movie-field">
                    @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="movie-field">
                    <div style="margin-top:10px;margin-left:15px">
                        <span style="font-weight:bold">Select File:</span>
                        <input type="file" name="postedFile">
                    </div>
                    <div class="col-md-offset-2 col-md-10" style="margin-top:25px;margin-left:0!important;">
                        <input style="width:50%; margin-top:30px;" type="submit" value="Create" class="btn btn-default">
                    </div>
                </div>
            </div>

            @*<div class="fields-row">
                <div class="movie-field">
                    <div class="col-md-offset-2 col-md-10" style="margin-left:0!important;">
                        <input style="width:50%; margin-top:30px;" type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>*@
        </div>
    }

    <div class="read-more" style="margin:0 0 0 17px;">
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

MoviesBlog/Views/Movies/Delete.cshtml
@model MoviesBlog.Models.Movie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete movie</h2>

<h3>Are you sure you want to delete this?</h3>
<div style="font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Producer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RunningTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RunningTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color read-more">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MoviesBlog/Views/Movies/Details.cshtml
@model MoviesBlog.Models.Movie

@{
    ViewBag.Title = "Details";
}

<h2>Details movie</h2>

<div>
    <hr />
    <dl class="dl-horizontal" style="font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Producer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RunningTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RunningTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language)
        </dd>

    </dl>
</div>
<p class="read-more">
    @if (Request.IsAuthenticated)
    {
        @Html.ActionLink("Edit | ", "Edit", new { id = Model.Id })
    }
    @Html.ActionLink("Back to List", "Index")
</p>

MoviesBlog/Views/Movies/Edit.cshtml
@model MoviesBlog.Models.Movie

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Movie</h2>


@using (Html.BeginForm("Edit", "Movies", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
        <div class="form-horizontal" style="font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="fields-row">
                <div class="movie-field">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="movie-field">
                    @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.Genre, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="fields-row">
                <div class="movie-field">
                    @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="movie-field">
                    @Html.LabelFor(model => model.Producer, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Producer, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Producer, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="fields-row">
                <div class="movie-field">
                    @Html.LabelFor(model => model.RunningTime, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.RunningTime, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RunningTime, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="movie-field">
                    @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.Language, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="fields-row">

                <div class="movie-field">
                    @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="movie-field">
                    <div style="margin-top:10px;margin-left:15px">
                        @Html.EditorFor(model => model.ImageName, new { htmlAttributes = new { @class = "image-name-edit"} })
                        @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
                        <span style="font-weight:bold">Select File:</span>
                        <input type="file" name="postedFile">
                    </div>
                    <div class="col-md-offset-2 col-md-10" style="margin-top:25px;margin-left:0!important;">
                        <input style="width:50%; margin-top:30px;" type="submit" value="Save" class="btn btn-default">
                    </div>
                </div>
            </div>
        </div>
}

<div class="read-more">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MoviesBlog/Views/Movies/Index.cshtml
@model IEnumerable<MoviesBlog.Models.Movie>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/d3")

<h3 class="filter-title">Filter movies by</h3>

<div class="container">
    @using (Html.BeginForm("", "Movies", FormMethod.Post, new { @class = "form-inline" }))
    {
    <div class="first-filter-row">
        <div class="form-group">
            @Html.TextBox("SearchName", "", new { @class = "form-control", placeholder = "Name" })
        </div>
        <div class="form-group">
            @Html.DropDownList("SearchGenre", EnumHelper.GetSelectList(typeof(MoviesBlog.Models.Genre)), "Genre", new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.DropDownList("SearchLanguage", EnumHelper.GetSelectList(typeof(MoviesBlog.Models.Language)), "Language", new { @class = "form-control" })
        </div>
    </div>
    <div class="second-filter-row">
        <div class="form-group">
            @Html.TextBox("searchReleaseDate", "", new { @class = "form-control", placeholder = "Since Year" })
        </div>
        <input class="btn btn-search-movies" type="submit" value="Search" />
    </div>
    }
</div>

<div style="margin-top: 50px; display: flex; justify-content: space-around;flex-wrap: wrap;">
    @foreach (var item in Model)
    {
        string img = !string.IsNullOrEmpty(item.ImageName) ? item.ImageName : "movie-default.jpg";

        <div style="width: 350px;">
            <div class="card u-clearfix">
                <div class="card-media">
                    <img src="@Url.Content("~/media/movies/" + img)" alt="" class="card-media-img" />
                    <a class="card-media-preview u-flex-center" href="@Url.Action("Trailer", new { id = item.Id })">
                        <svg fill="#ffffff" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                            <path d="M8 5v14l11-7z" />
                            <path d="M0 0h24v24H0z" fill="none" />
                        </svg>
                    </a>
                    <span class="card-media-tag card-media-tag-orange">@item.Genre</span>
                </div>

                <div class="card-body">
                    <div class="card-body-title">
                        <h4 style="width:45%;" class="card-body-heading">@Html.ActionLink(@item.Name, "Details", new { id = item.Id })</h4>
                        <div class="card-body-stars u-clearfix">
                            <div class="first-row" style="display:inline-flex;">
                                <svg fill="#ebb91a" height="25" viewBox="0 0 18 18" width="25" xmlns="http://www.w3.org/2000/svg" style="margin-top:-3px;">
                                    <path d="M9 11.3l3.71 2.7-1.42-4.36L15 7h-4.55L9 2.5 7.55 7H3l3.71 2.64L5.29 14z" />
                                    <path d="M0 0h18v18H0z" fill="none" />
                                </svg>
                                <span class="imdbRating"> </span>
                            </div>
                            <div class="second-row">
                                <span class="imdbVoters"></span>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="small-text">@item.RunningTime minutes | @item.Language</div>
                    <div class="">Released: @item.ReleaseDate.ToShortDateString()</div>
                    <div>Producer: @item.Producer</div>
                    @if (Request.IsAuthenticated)
                    {
                        <div>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                        </div>
                    }
                </div>
            </div>
    }
    <script>
        updateMoviesRate();
    </script>
</div>